FROM node:14-alpine

WORKDIR /app
COPY rollup.config.js ./
COPY package*.json ./
RUN npm install

COPY ./src ./src
COPY ./public ./public

COPY ./sigterm-handler.sh /usr/local/bin/sigterm-handler.sh
RUN chmod +x /usr/local/bin/sigterm-handler.sh

EXPOSE 5000
ENV HOST=0.0.0.0
ENTRYPOINT sigterm-handler.sh
