version: "3.9"

services:
  app:
    image: form-questions
    build:
      dockerfile: ./Dockerfile-dev
    environment:
      VITE_PUBLIC_BASE_URL: ${PUBLIC_BASE_URL}
      VITE_GAPI_API_KEY: ${GAPI_API_KEY}
      VITE_GAPI_CLIENT_ID: ${GAPI_CLIENT_ID}
      VITE_GAPI_PROJECT_NUMBER: ${GAPI_PROJECT_NUMBER}
    volumes:
      - .:/usr/src/form-questions
    ports:
      - 80:3000
      - 3000:3000
