FROM node:14-alpine

WORKDIR /app
COPY rollup.config.js ./
COPY package*.json ./
RUN npm install

COPY ./src ./src
COPY ./public ./public
COPY ./.env ./.env

RUN npm run build

EXPOSE 5000
ENV HOST=0.0.0.0
ENTRYPOINT npm start build
