version: "3.9"

services:
  app:
    image: form-questions
    build: {}
    environment:
      GAPI_CLIENT_ID: ${GAPI_CLIENT_ID}
      GAPI_CLIENT_SECRET: ${GAPI_CLIENT_SECRET}
    ports:
      - 80:3000
      - 3000:3000
